const qt = @import("qt.zig");
const c = qt.c;

const Icon = @This();
const Widget = qt.widgets.Widget;

// TODO
pub const InitOptions = struct {
    parent: ?*Widget = null,
};

pub fn init(opts: InitOptions) *Icon {
    return @ptrCast(c.QtC_Icon_new(
        @ptrCast(opts.parent),
    ));
}

pub fn fromTheme(icon: ThemeIcon) *Icon {
    return @ptrCast(c.QtC_Icon_fromTheme(
        @intFromEnum(icon),
    ));
}

pub fn deinit(self: *Icon) void {
    c.QtC_Icon_delete(@ptrCast(self));
}

pub fn widget(self: *Icon) *Widget {
    return @ptrCast(self);
}

pub const ThemeIcon = enum(c_uint) {
    address_book_new = c.QtC_Icon_ThemeIcon_AddressBookNew,
    application_exit = c.QtC_Icon_ThemeIcon_ApplicationExit,
    appointment_new = c.QtC_Icon_ThemeIcon_AppointmentNew,
    call_start = c.QtC_Icon_ThemeIcon_CallStart,
    call_stop = c.QtC_Icon_ThemeIcon_CallStop,
    contact_new = c.QtC_Icon_ThemeIcon_ContactNew,
    document_new = c.QtC_Icon_ThemeIcon_DocumentNew,
    document_open = c.QtC_Icon_ThemeIcon_DocumentOpen,
    document_open_recent = c.QtC_Icon_ThemeIcon_DocumentOpenRecent,
    document_page_setup = c.QtC_Icon_ThemeIcon_DocumentPageSetup,
    document_print = c.QtC_Icon_ThemeIcon_DocumentPrint,
    document_print_preview = c.QtC_Icon_ThemeIcon_DocumentPrintPreview,
    document_properties = c.QtC_Icon_ThemeIcon_DocumentProperties,
    document_revert = c.QtC_Icon_ThemeIcon_DocumentRevert,
    document_save = c.QtC_Icon_ThemeIcon_DocumentSave,
    document_save_as = c.QtC_Icon_ThemeIcon_DocumentSaveAs,
    document_send = c.QtC_Icon_ThemeIcon_DocumentSend,
    edit_clear = c.QtC_Icon_ThemeIcon_EditClear,
    edit_copy = c.QtC_Icon_ThemeIcon_EditCopy,
    edit_cut = c.QtC_Icon_ThemeIcon_EditCut,
    edit_delete = c.QtC_Icon_ThemeIcon_EditDelete,
    edit_find = c.QtC_Icon_ThemeIcon_EditFind,
    edit_paste = c.QtC_Icon_ThemeIcon_EditPaste,
    edit_redo = c.QtC_Icon_ThemeIcon_EditRedo,
    edit_select_all = c.QtC_Icon_ThemeIcon_EditSelectAll,
    edit_undo = c.QtC_Icon_ThemeIcon_EditUndo,
    folder_new = c.QtC_Icon_ThemeIcon_FolderNew,
    format_indent_less = c.QtC_Icon_ThemeIcon_FormatIndentLess,
    format_indent_here = c.QtC_Icon_ThemeIcon_FormatIndentMore,
    format_justify_center = c.QtC_Icon_ThemeIcon_FormatJustifyCenter,
    format_justify_fill = c.QtC_Icon_ThemeIcon_FormatJustifyFill,
    format_justify_left = c.QtC_Icon_ThemeIcon_FormatJustifyLeft,
    format_justify_right = c.QtC_Icon_ThemeIcon_FormatJustifyRight,
    format_text_direction_ltr = c.QtC_Icon_ThemeIcon_FormatTextDirectionLtr,
    format_text_direction_rtl = c.QtC_Icon_ThemeIcon_FormatTextDirectionRtl,
    format_text_bold = c.QtC_Icon_ThemeIcon_FormatTextBold,
    format_text_italic = c.QtC_Icon_ThemeIcon_FormatTextItalic,
    format_text_underline = c.QtC_Icon_ThemeIcon_FormatTextUnderline,
    format_text_strikethrough = c.QtC_Icon_ThemeIcon_FormatTextStrikethrough,
    go_down = c.QtC_Icon_ThemeIcon_GoDown,
    go_home = c.QtC_Icon_ThemeIcon_GoHome,
    go_next = c.QtC_Icon_ThemeIcon_GoNext,
    go_previous = c.QtC_Icon_ThemeIcon_GoPrevious,
    go_up = c.QtC_Icon_ThemeIcon_GoUp,
    help_about = c.QtC_Icon_ThemeIcon_HelpAbout,
    help_faq = c.QtC_Icon_ThemeIcon_HelpFaq,
    insert_image = c.QtC_Icon_ThemeIcon_InsertImage,
    insert_link = c.QtC_Icon_ThemeIcon_InsertLink,
    insert_text = c.QtC_Icon_ThemeIcon_InsertText,
    list_add = c.QtC_Icon_ThemeIcon_ListAdd,
    list_remove = c.QtC_Icon_ThemeIcon_ListRemove,
    mail_forward = c.QtC_Icon_ThemeIcon_MailForward,
    mail_mark_important = c.QtC_Icon_ThemeIcon_MailMarkImportant,
    mail_mark_read = c.QtC_Icon_ThemeIcon_MailMarkRead,
    mail_mark_unread = c.QtC_Icon_ThemeIcon_MailMarkUnread,
    mail_message_new = c.QtC_Icon_ThemeIcon_MailMessageNew,
    mail_reply_all = c.QtC_Icon_ThemeIcon_MailReplyAll,
    mail_reply_sender = c.QtC_Icon_ThemeIcon_MailReplySender,
    mail_send = c.QtC_Icon_ThemeIcon_MailSend,
    media_eject = c.QtC_Icon_ThemeIcon_MediaEject,
    media_playback_pause = c.QtC_Icon_ThemeIcon_MediaPlaybackPause,
    media_playback_start = c.QtC_Icon_ThemeIcon_MediaPlaybackStart,
    media_playback_stop = c.QtC_Icon_ThemeIcon_MediaPlaybackStop,
    media_record = c.QtC_Icon_ThemeIcon_MediaRecord,
    media_seek_backward = c.QtC_Icon_ThemeIcon_MediaSeekBackward,
    media_seek_forward = c.QtC_Icon_ThemeIcon_MediaSeekForward,
    media_skip_backward = c.QtC_Icon_ThemeIcon_MediaSkipBackward,
    media_skip_forward = c.QtC_Icon_ThemeIcon_MediaSkipForward,
    object_rotate_left = c.QtC_Icon_ThemeIcon_ObjectRotateLeft,
    object_rotate_right = c.QtC_Icon_ThemeIcon_ObjectRotateRight,
    process_stop = c.QtC_Icon_ThemeIcon_ProcessStop,
    system_lock_screen = c.QtC_Icon_ThemeIcon_SystemLockScreen,
    system_log_out = c.QtC_Icon_ThemeIcon_SystemLogOut,
    system_search = c.QtC_Icon_ThemeIcon_SystemSearch,
    system_reboot = c.QtC_Icon_ThemeIcon_SystemReboot,
    system_shutdown = c.QtC_Icon_ThemeIcon_SystemShutdown,
    tools_check_spelling = c.QtC_Icon_ThemeIcon_ToolsCheckSpelling,
    view_fullscreen = c.QtC_Icon_ThemeIcon_ViewFullscreen,
    view_refresh = c.QtC_Icon_ThemeIcon_ViewRefresh,
    view_restore = c.QtC_Icon_ThemeIcon_ViewRestore,
    window_close = c.QtC_Icon_ThemeIcon_WindowClose,
    window_new = c.QtC_Icon_ThemeIcon_WindowNew,
    zoom_fit_best = c.QtC_Icon_ThemeIcon_ZoomFitBest,
    zoom_in = c.QtC_Icon_ThemeIcon_ZoomIn,
    zoom_out = c.QtC_Icon_ThemeIcon_ZoomOut,
    audio_card = c.QtC_Icon_ThemeIcon_AudioCard,
    audio_input_microphone = c.QtC_Icon_ThemeIcon_AudioInputMicrophone,
    battery = c.QtC_Icon_ThemeIcon_Battery,
    camera_photo = c.QtC_Icon_ThemeIcon_CameraPhoto,
    camera_video = c.QtC_Icon_ThemeIcon_CameraVideo,
    camera_web = c.QtC_Icon_ThemeIcon_CameraWeb,
    computer = c.QtC_Icon_ThemeIcon_Computer,
    drive_harddisk = c.QtC_Icon_ThemeIcon_DriveHarddisk,
    drive_optical = c.QtC_Icon_ThemeIcon_DriveOptical,
    input_gaming = c.QtC_Icon_ThemeIcon_InputGaming,
    input_keyboard = c.QtC_Icon_ThemeIcon_InputKeyboard,
    input_mouse = c.QtC_Icon_ThemeIcon_InputMouse,
    input_tablet = c.QtC_Icon_ThemeIcon_InputTablet,
    media_flash = c.QtC_Icon_ThemeIcon_MediaFlash,
    media_optical = c.QtC_Icon_ThemeIcon_MediaOptical,
    media_tape = c.QtC_Icon_ThemeIcon_MediaTape,
    multimedia_player = c.QtC_Icon_ThemeIcon_MultimediaPlayer,
    network_wired = c.QtC_Icon_ThemeIcon_NetworkWired,
    network_wireless = c.QtC_Icon_ThemeIcon_NetworkWireless,
    phone = c.QtC_Icon_ThemeIcon_Phone,
    printer = c.QtC_Icon_ThemeIcon_Printer,
    scanner = c.QtC_Icon_ThemeIcon_Scanner,
    video_display = c.QtC_Icon_ThemeIcon_VideoDisplay,
    appointment_missed = c.QtC_Icon_ThemeIcon_AppointmentMissed,
    appointment_soon = c.QtC_Icon_ThemeIcon_AppointmentSoon,
    audio_volume_high = c.QtC_Icon_ThemeIcon_AudioVolumeHigh,
    audio_volume_low = c.QtC_Icon_ThemeIcon_AudioVolumeLow,
    audio_volume_medium = c.QtC_Icon_ThemeIcon_AudioVolumeMedium,
    audio_volume_muted = c.QtC_Icon_ThemeIcon_AudioVolumeMuted,
    battery_caution = c.QtC_Icon_ThemeIcon_BatteryCaution,
    battery_low = c.QtC_Icon_ThemeIcon_BatteryLow,
    dialog_error = c.QtC_Icon_ThemeIcon_DialogError,
    dialog_information = c.QtC_Icon_ThemeIcon_DialogInformation,
    dialog_password = c.QtC_Icon_ThemeIcon_DialogPassword,
    dialog_question = c.QtC_Icon_ThemeIcon_DialogQuestion,
    dialog_warning = c.QtC_Icon_ThemeIcon_DialogWarning,
    folder_drag_accept = c.QtC_Icon_ThemeIcon_FolderDragAccept,
    folder_open = c.QtC_Icon_ThemeIcon_FolderOpen,
    folder_visiting = c.QtC_Icon_ThemeIcon_FolderVisiting,
    image_loading = c.QtC_Icon_ThemeIcon_ImageLoading,
    image_missing = c.QtC_Icon_ThemeIcon_ImageMissing,
    mail_attachment = c.QtC_Icon_ThemeIcon_MailAttachment,
    mail_unread = c.QtC_Icon_ThemeIcon_MailUnread,
    mail_read = c.QtC_Icon_ThemeIcon_MailRead,
    mail_replied = c.QtC_Icon_ThemeIcon_MailReplied,
    media_playlist_repeat = c.QtC_Icon_ThemeIcon_MediaPlaylistRepeat,
    media_playlist_shuffle = c.QtC_Icon_ThemeIcon_MediaPlaylistShuffle,
    network_offline = c.QtC_Icon_ThemeIcon_NetworkOffline,
    printer_printing = c.QtC_Icon_ThemeIcon_PrinterPrinting,
    security_high = c.QtC_Icon_ThemeIcon_SecurityHigh,
    security_low = c.QtC_Icon_ThemeIcon_SecurityLow,
    software_update_available = c.QtC_Icon_ThemeIcon_SoftwareUpdateAvailable,
    software_update_urgent = c.QtC_Icon_ThemeIcon_SoftwareUpdateUrgent,
    sync_error = c.QtC_Icon_ThemeIcon_SyncError,
    sync_synchronizing = c.QtC_Icon_ThemeIcon_SyncSynchronizing,
    user_abailable = c.QtC_Icon_ThemeIcon_UserAvailable,
    user_offline = c.QtC_Icon_ThemeIcon_UserOffline,
    weather_clear = c.QtC_Icon_ThemeIcon_WeatherClear,
    weather_clear_night = c.QtC_Icon_ThemeIcon_WeatherClearNight,
    weather_few_clouds = c.QtC_Icon_ThemeIcon_WeatherFewClouds,
    weather_few_clouds_night = c.QtC_Icon_ThemeIcon_WeatherFewCloudsNight,
    weather_fog = c.QtC_Icon_ThemeIcon_WeatherFog,
    weather_showers = c.QtC_Icon_ThemeIcon_WeatherShowers,
    weather_snow = c.QtC_Icon_ThemeIcon_WeatherSnow,
    weather_storm = c.QtC_Icon_ThemeIcon_WeatherStorm,
};
